pipeline {

    agent any

    tools {
        maven "mvn-3.6"
        jdk "jdk-13"
    }

    environment {
        COMMIT_AUTHOR = ""
        COMMIT_MESSAGE = ""
        PROJECT_VERSION = ""
        COMMIT_URL = ""
        MAVEN_HOME = tool 'mvn-3.6'
    }

    stages {
        stage("Seting environment") {
            steps {
                script {
                    pom = readMavenPom file:"pom.xml"
                    PROJECT_VERSION = pom.version
                    COMMIT_MESSAGE = sh script: "git show -s --pretty='%s'", returnStdout: true
                    COMMIT_MESSAGE = COMMIT_MESSAGE.trim()
                    COMMIT_AUTHOR = sh script: "git show -s --pretty='%cn <%ce>'", returnStdout: true
                    COMMIT_AUTHOR = COMMIT_AUTHOR.trim()
                    COMMIT_URL = GIT_URL + "/commit/" + GIT_COMMIT
                }
            }
        }
        stage("SonarQube Analysis") {
            steps {
                withSonarQubeEnv(installationName: "sonarqube", credentialsId: "sonarqube-token") {
                    sh "${MAVEN_HOME}/bin/mvn clean verify sonar:sonar -Dsonar.projectKey=Jamsek-m_kee-auth_AYHN33_2ZY2MFTYvVt0R"
                }
            }
        }
        stage("Run tests") {
            steps {
                sh "mvn clean test"
            }
        }
        stage("Deploy library") {
            steps {
                withCredentials([usernamePassword(credentialsId: 'nexus-username', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')]) {
                    sh "mvn clean deploy -Dci.nexus.user=$USERNAME -Dci.nexus.pass=$PASSWORD --settings .ci/settings.xml -DskipTests=true"
                }
            }
        }
    }

    post {
        success {
            slackSend (color: '#00FF00', message: "SUCCESSFUL: Job '${env.JOB_NAME}' [<${env.BUILD_URL}|${env.BUILD_NUMBER}>]:\n'<${COMMIT_URL}|${COMMIT_MESSAGE}>' _from ${COMMIT_AUTHOR}_")
        }
        failure {
            slackSend (color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME}' [<${env.BUILD_URL}|${env.BUILD_NUMBER}>]:\n'<${COMMIT_URL}|${COMMIT_MESSAGE}>' _from ${COMMIT_AUTHOR}_")
        }
    }
}
