kee-auth:
  clients:
    # client mapping - key is client name (used in application), value is client id (used by provider). if no mapping is provided, it is assumed id and name match
    test-service: kee-auth-test
  oidc:
    # if true, endpoints and jwks will be automatically fetched from .well-known url
    auto-configure: true
    issuer: https://keycloak.example.com/auth
    well-known-url: https://keycloak.example.com/auth/realms/kee-auth-test/.well-known/openid-configuration
    use-jwks-uri: true
    jwks-url: https://keycloak.example.com/auth/realms/kee-auth-test/protocol/openid-connect/certs
    # used for client credentials flow
    client-credentials:
      client-id: kee-auth-test
      client-secret: e7820cf7-fbfb-4397-b156-91b15a2e3
      token-url: https://keycloak.example.com/auth/realms/kee-auth-test/protocol/openid-connect/token
    credentials:
      location: header # header | cookie
      cookie-name: authorization
      header-name: Authorization
  jwt:
    # leeway when checking token expiration
    time-leeway: 1
    # claim mappings (with default values)
    claims:
      id: sub
      email: email
      username: preferred_username
      scope: scope
    keys:
      - kid: g7j
        alg: HS256
        secret: secretkey
      - kid: d5i
        alg: RS256
        n: 'qtzjj3KuFldrDL3rpIsKoEjzxwHQEUmzQNHoCP8CYiA-29q-Tqt8s0ALg5ruK-UH5pBJxtixEuYG0jkNcHFLOfJz45W2Lc1kjYtOQbjMEDewrCG2pDDT-kBbjs_GaaOINQfV5e1Duv9BYpHSaQtrin-yeOX4Lu5U6qTRzuSo-bO29dB6Vr5Lj8vhEUm5vQE9RvsM1ZyXwGV6LLwi-cerfEhKgHhfoUzGuZqB4EI74LoyPytxTafb53tSz2eccALjTdfor03NUae89qiOC11FGw0gVteoplkW7nH6dVMwfTfByGb6fTzYy2Yx_30kCO6yNwALQdDujJNxs2Y332w'
        e: 'ATEF'
      - kid: 7e9
        alg: RS256
        x5c: 'MIIClTCCAX0CBgF3ISs0kjANBgkqhkiG9w0BAQsFADAOMQwwCgYDVQQDDANrcnYwHhcNMjEwMTIwMTg1ODM1WhcNMzEwMTIwMTkwMDE1WjAOMQwwCgYDVQQDDANrcnYwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCq3OOPcq4WV2sMveukiwqgSPPHAdARSbNA0egI/wJiID7b2r5Oq3yzQAuDmu4r5QfmkEnG2LES5gbSOQ1wcUs58nPjlbYtzWSNi05BuMwQN7CsIbakMNP6QFuOz8Zpo4g1B9Xl7UO6/0FikdJpC2uKf7J45fgu7lTqpNHO5Kj5s7b10HpWvkuPy+ERSbm9AT1Ha+wzVnJfAZXosvCL5w4VFl8SEqAeF+hTMa5moHgQjvgujI/K3FMOC4De1LPZ5xwAuNN1+ivTc1RIJ32qI4LXUUbDSBW16imWRbucfp1UzB9N8HIZvp9PNjLZjH/fSQI7rI3AAtB0O6Mk3GzZiffbAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAKAT+e2wVNEJld5CCtpqN13fvCJw7Yc2HZdeg648JqkrLOVyZltynMA2VG6NM4sDwQcH3Cb75nPcfND+rUrTSDiu0eQ3xfCh4pfsqvh8EEQ95yrGGm91McdGlNt24IUZNfGFzGZs/cCfuxoQUfpMCSSlVN/6SFpm8E5wHMYP9ALR+Aw8eVWMOOpDDzQWDZHo7lxkz4rMuaeWqOggAsdsrEblpWoU52Mxy02x+I8GUJdxjwL1atRI1yuUp7LkZ1O+NsdedOvHpUlDGRPIbF2VfeurrIIs0y2Pz1TdCR5eSxjVHPleiabaKjWft8qUysGGptTr+FmGj9KGad4L8='
      - kid: 1a5
        alg: ES256
        crv: P-256
        x: 'JNfdsl9xilwKKw4au3X0YrEQ3p9KXmtl_FAz-W6sdc'
        y: 'K5W777lR8cRZFOg7aUhAJY9_T1Is3oTo6LHr43gsA'
  role-resolvers:
    default:
      roles-mapping: roles
      enabled: true
    keycloak:
      enabled: true